=== gitter-badger/aeq-ts3-bot/aeq-ts3-bot-core/src/main/resources/aeq-ts3-bot-configuration.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  ~ MIT License
  ~
  ~ Copyright (c) 2017 Lukas Kannenberg
  ~
  ~ Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
  ~ documentation files (the "Software"), to deal in the Software without restriction, including without limitation
  ~ the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
  ~ to permit persons to whom the Software is furnished to do so, subject to the following conditions:
  ~
  ~ The above copyright notice and this permission notice shall be included in all copies or substantial portions of
  ~ the Software.
  ~
  ~ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
  ~ THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  ~ AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
  ~ CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
  ~ IN THE SOFTWARE.
  -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.w3schools.com"
           elementFormDefault="qualified">

    <xs:element name="configuration">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="server">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="hostname"/>
                            <xs:element name="query-port"/>
                            <xs:element name="virtual-server-port"/>
                            <xs:element name="password" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="permissions" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="query-user"/>
                            <xs:element name="query-key"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== gitter-badger/aeq-ts3-bot/config/aeq-ts3-bot-configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ MIT License
  ~
  ~ Copyright (c) 2017 Lukas Kannenberg
  ~
  ~ Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
  ~ documentation files (the "Software"), to deal in the Software without restriction, including without limitation
  ~ the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
  ~ to permit persons to whom the Software is furnished to do so, subject to the following conditions:
  ~
  ~ The above copyright notice and this permission notice shall be included in all copies or substantial portions of
  ~ the Software.
  ~
  ~ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
  ~ THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  ~ AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
  ~ CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
  ~ IN THE SOFTWARE.
  -->

<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="http://www.w3schools.com"
               xsi:schemaLocation="http://www.w3schools.com aeq-ts3-bot-configuration.xsd">
    <name>Merlin</name>
    <server>
        <hostname>137.74.223.0</hostname>
        <query-port>10011</query-port>
        <virtual-server-port>9889</virtual-server-port>
    </server>
    <permissions>
        <query-user>aeq-ts3-bot</query-user>
        <query-key>bDiaX5Az</query-key>
    </permissions>
</configuration>
